###
GET localhost:9090/coffees

###
GET http://localhost:9090/coffees/1

###
POST localhost:9090/coffees
Content-Type: application/json

{
  "id": "4",
  "name": "new Espresso",
  "price": 2500
}

###
PUT localhost:9090/coffees/6
Content-Type: application/json

{
  "id": "6",
  "name": "new right Espresso",
  "price": 2500
}

###
DELETE localhost:9090/coffees/1