###
GET localhost:8080/coffees

###
GET http://localhost:8080/coffees/1e79177f-5fba-445a-a5e4-1bae47e0e060

###
POST localhost:8080/coffees
Content-Type: application/json

{
  "id": "d6435e8c-348c-4359-94ee-d0cf92102c6",
  "name": "Espresso"
}

###
PUT localhost:8080/coffees/baed2220-125b-4902-b713-80e2404f291
Content-Type: application/json

{
  "name": "new right Espresso"
}

###
DELETE localhost:8080/coffees/d6435e8c-348c-4359-94ee-d0cf92102c